version: v1
mig-configs:
  all-disabled:
    - devices: all
      mig-enabled: false

  all-enabled:
    - devices: all
      mig-enabled: true
      mig-devices: {}

  all-cryosparc:
    - devices: all
      mig-enabled: true
      mig-devices:
        "2g.10gb": 2
        "3g.20gb": 1
